default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project_development_2021

test:
  <<: *default
  database: project_test_2021

production:
  <<: *default
  database: project_production
  username: 
  password: 